<?php

// autoload_classmap.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'lessc' => $baseDir . '/lib/leafo/lessphp/lessc.inc.php',
    'lessc_parser' => $baseDir . '/lib/leafo/lessphp/lessc.inc.php',
    'lessc_formatter_classic' => $baseDir . '/lib/leafo/lessphp/lessc.inc.php',
    'lessc_formatter_compressed' => $baseDir . '/lib/leafo/lessphp/lessc.inc.php',
    'lessc_formatter_lessjs' => $baseDir . '/lib/leafo/lessphp/lessc.inc.php',
);
