imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: vendor/assetic.yml }
    - { resource: vendor/twig.yml }
    - { resource: vendor/monolog.yml }
    - { resource: vendor/swiftmailer.yml }
    - { resource: vendor/doctrine.yml }
    - { resource: vendor/sensio_framework_extra.yml }
    - { resource: vendor/fos_comment.yml }
    - { resource: vendor/fos_user.yml }
    - { resource: vendor/jms_serializer.yml }
    - { resource: vendor/stof_doctrine_extensions.yml }

framework:
    #esi:             ~
    secret:     %secret%
    translator: { fallback: fr }
    router:
        resource:            "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:                true
    csrf_protection:     true
    validation:          { enable_annotations: true }
    templating:          { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:      fr
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:             ~




