imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: false
    intercept_redirects: false

monolog:
    handlers:
        dev_event:
            type: stream
            level: debug
            path: %kernel.logs_dir%/%kernel.environment%_event.log
            formatter: monolog.formatter.session_request
            channels: event
        dev_request:
            type: stream
            level: debug
            path: %kernel.logs_dir%/%kernel.environment%_request.log
            formatter: monolog.formatter.session_request
            channels: request
        dev_doctrine:
            type: stream
            level: debug
            path: %kernel.logs_dir%/%kernel.environment%_doctrine.log
            formatter: monolog.formatter.session_request
            channels: doctrine
        dev_app:
            type: stream
            level: debug
            path: %kernel.logs_dir%/%kernel.environment%_app.log
            formatter: monolog.formatter.session_request
            channels: app
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com
